export const PERMISSION_CONST = {
  MODEL_NAME: 'permission',
  MODEL_PROVIDER: 'PERMISSION_MODEL',
};

export enum PermissionType {
  // Users
  CREATE_USER = 'CREATE_USER',
  READ_USER = 'READ_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  // Roles
  CREATE_ROLE = 'CREATE_ROLE',
  READ_ROLE = 'READ_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',

  // Permissions
  CREATE_PERMISSION = 'CREATE_PERMISSION',
  READ_PERMISSION = 'READ_PERMISSION',
  UPDATE_PERMISSION = 'UPDATE_PERMISSION',
  DELETE_PERMISSION = 'DELETE_PERMISSION',

  //Tests
  CREATE_TEST = 'CREATE_TEST',
  READ_TEST = 'READ_TEST',
  UPDATE_TEST = 'UPDATE_TEST',
  DELETE_TEST = 'DELETE_TEST',

  //Exams
  CREATE_EXAM = 'CREATE_EXAM',
  READ_EXAM = 'READ_EXAM',
  UPDATE_EXAM = 'UPDATE_EXAM',
  DELETE_EXAM = 'DELETE_EXAM',

  //Topics
  CREATE_TOPIC = 'CREATE_TOPIC',
  READ_TOPIC = 'READ_TOPIC',
  UPDATE_TOPIC = 'UPDATE_TOPIC',
  DELETE_TOPIC = 'DELETE_TOPIC',

  //Levels
  CREATE_LEVEL = 'CREATE_LEVEL',
  READ_LEVEL = 'READ_LEVEL',
  UPDATE_LEVEL = 'UPDATE_LEVEL',
  DELETE_LEVEL = 'DELETE_LEVEL',

  //Subjects
  CREATE_SUBJECT = 'CREATE_SUBJECT',
  READ_SUBJECT = 'READ_SUBJECT',
  UPDATE_SUBJECT = 'UPDATE_SUBJECT',
  DELETE_SUBJECT = 'DELETE_SUBJECT',

  //Questions
  CREATE_QUESTIONS = 'CREATE_QUESTIONS',
  READ_QUESTIONS = 'READ_QUESTIONS',
  UPDATE_QUESTIONS = 'UPDATE_QUESTIONS',
  DELETE_QUESTIONS = 'DELETE_QUESTIONS',

  //Answers
  CREATE_ANSWER = 'CREATE_ANSWER',
  READ_ANSWER = 'READ_ANSWER',
  UPDATE_ANSWER = 'UPDATE_ANSWER',
  DELETE_ANSWER = 'DELETE_ANSWER',

  //Answers
  CREATE_FEEDBACK = 'CREATE_FEEDBACK',
  READ_FEEDBACK = 'READ_FEEDBACK',
  UPDATE_FEEDBACK = 'UPDATE_FEEDBACK',
  DELETE_FEEDBACK = 'DELETE_FEEDBACK',

  //Profiles
  CREATE_PROFILE = 'CREATE_PROFILE',
  READ_PROFILE = 'READ_PROFILE',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  DELETE_PROFILE = 'DELETE_PROFILE',
}
