export const EXCEPTION_PUBLIC_NOTIFICATION = {
  PUBLIC_NOTIFICATION_NOT_FOUND: {
    message: 'PUBLIC NOTIFICATION NOT FOUND',
    code: 'pn001',
  },
  PUBLIC_NOTIFICATION_EXISTED: {
    message: 'PUBLIC NOTIFICATION EXISTED',
    code: 'pn002',
  },
  PUBLIC_NOTIFICATION_DOES_NOT_EXIST: {
    message: 'PUBLIC NOTIFICATION EXISTED',
    code: 'pn003',
  },
};
